# GoPKI golangci-lint configuration
# Optimized for cryptographic library with focus on security and performance

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  # Security-focused settings
  gosec:
    # Security rules for crypto libraries
    severity: "medium"
    confidence: "medium"
    excludes:
      - G501  # Allow MD5 for non-security purposes (like checksums)
    includes:
      - G101  # Look for hardcoded credentials
      - G102  # Bind to all interfaces
      - G103  # Audit the use of unsafe block
      - G104  # Audit errors not checked
      - G106  # Audit the use of ssh.InsecureIgnoreHostKey
      - G107  # Url provided to HTTP request as taint input
      - G108  # Profiling endpoint automatically exposed
      - G109  # Potential Integer overflow made by strconv.Atoi result conversion
      - G110  # Potential DoS vulnerability via decompression bomb

  # Code quality settings
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Struct field alignment can be relaxed for clarity
      - shadow         # Enable predeclared linter separately

  gocyclo:
    min-complexity: 15  # Allow moderate complexity for crypto operations

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jasoet/gopki

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  misspell:
    locale: US
    ignore-words:
      - keypair
      - keypairs

  lll:
    line-length: 120  # Reasonable for complex crypto function signatures

  unused:
    check-exported: false  # Public API may have unused exported functions

  staticcheck:
    checks: ["all"]

  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  # Performance settings
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  # Style settings
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID", "URL", "HTTP", "JSON", "API", "PKI", "CA", "RSA", "ECDSA", "Ed25519", "X509", "PEM", "DER", "PKCS", "CMS", "OID"] # Allow crypto acronyms
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

linters:
  enable:
    # Code quality
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - predeclared

    # Security (critical for crypto library)
    - gosec

    # Performance
    - prealloc
    - unconvert

    # Style and maintainability
    - gofmt
    - goimports
    - misspell
    - lll
    - goconst
    - gocyclo
    - revive

    # Bug prevention
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck

    # Additional useful linters
    - asciicheck
    - gofumpt
    - whitespace
    - wsl

  disable:
    # Disabled linters with reasons
    - dupl         # Crypto code may have similar patterns legitimately
    - funlen       # Crypto functions can be long due to security checks
    - gocognit     # Cognitive complexity can be high in crypto code
    - nestif       # Deep nesting acceptable for security validations
    - cyclop       # Duplicate of gocyclo
    - exhaustive   # Not all enum cases need handling in crypto contexts
    - forbidigo    # May conflict with necessary crypto operations
    - forcetypeassert # Type assertions are sometimes necessary in crypto
    - godot        # Comment formatting can be relaxed
    - godox        # Allow TODOs in development
    - gomnd        # Magic numbers acceptable in crypto (key sizes, etc.)
    - gomoddirectives # Module directives are project-specific
    - gomodguard   # Module restrictions not needed
    - importas     # Import aliasing flexibility needed
    - maintidx     # Maintainability index can be relaxed for crypto
    - nlreturn     # Newline returns formatting is subjective
    - paralleltest # Crypto tests may need sequential execution
    - testpackage  # Tests can be in same package for access to internals
    - wrapcheck    # Error wrapping patterns can vary

issues:
  exclude-dirs:
    - vendor
    - examples  # Examples may have API mismatches during development
    - encryption  # Temporarily excluded due to API updates
    - pkcs12     # Temporarily excluded due to API updates

  exclude-files:
    - ".*\\.pb\\.go$"  # Exclude generated protobuf files

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec        # Security checks can be relaxed in tests
        - goconst      # Test constants can be repeated
        - lll          # Test lines can be longer
        - dupl         # Test code duplication is acceptable

    # Exclude specific issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
      # Allow weak crypto in examples or specific documented cases

    # Allow long functions in signer/verifier (complex crypto operations)
    - path: (signer|verifier)\.go
      linters:
        - funlen
        - gocyclo

    # Allow complexity in format implementations
    - path: formats/.*\.go
      linters:
        - gocyclo
        - goconst

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - revive
      severity: warning
    - linters:
        - gosec
      severity: error  # Security issues are always errors