name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: 20

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    # Only run on push to main branch or manual trigger
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Install dependencies
      - name: Download dependencies
        run: go mod download

      # Verify dependencies
      - name: Verify dependencies
        run: go mod verify

      # Run tests with race detection and coverage
      - name: Run unit tests
        run: go test ./... -race -coverprofile=coverage.out

      # Run compatibility tests
      - name: Run compatibility tests
        run: go test -tags compatibility ./compatibility/...

      # Run examples to ensure they work
      - name: Test examples
        run: |
          echo "Testing examples compilation..."
          go build -tags example ./examples/keypair/main.go
          go build -tags example ./examples/certificates/main.go
          go build -tags example ./examples/signing/main.go
          go build -tags example ./examples/encryption/main.go
          echo "All examples compiled successfully"

      # Upload coverage to GitHub
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    # Only run after tests pass
    needs: test
    # Only run on push to main branch or manual trigger
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    permissions:
      contents: write # Needed for creating releases and tags
      issues: write   # Needed for creating/labeling issues
      pull-requests: write # Needed for creating/labeling PRs

    steps:
      # Checkout repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # Use GITHUB_TOKEN for auth

      # Setup Node.js for semantic-release
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install semantic-release and plugins
      - name: Install semantic-release
        run: |
          npm init -y
          npm install --save-dev \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/github \
            @semantic-release/git \
            conventional-changelog-conventionalcommits

      # Run semantic-release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release