name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: 20

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    # Only run on push to main branch or manual trigger
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    permissions:
      contents: write # Needed for creating releases and tags
      issues: write   # Needed for creating/labeling issues
      pull-requests: write # Needed for creating/labeling PRs

    steps:
      # Checkout repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # Use GITHUB_TOKEN for auth

      # Setup Node.js for semantic-release
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install semantic-release and plugins
      - name: Install semantic-release
        run: |
          npm init -y
          npm install --save-dev \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/github \
            @semantic-release/git \
            conventional-changelog-conventionalcommits

      # Run semantic-release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release