name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: 20

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    # Only run on push to main branch or manual trigger
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Install Task
      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      # Install dependencies
      - name: Download dependencies
        run: go mod download

      # Verify dependencies
      - name: Verify dependencies
        run: go mod verify

      # Run tests using Taskfile (main tests only, exclude examples and compatibility)
      - name: Run unit tests
        run: task test

      # Upload coverage to GitHub
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: output/coverage.out

  compatibility-tests:
    name: Compatibility Tests
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    continue-on-error: true # Don't fail the workflow if this job fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Download dependencies
        run: go mod download

      - name: Run compatibility tests
        run: task test:compatibility

  examples:
    name: Run Examples
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    continue-on-error: true # Don't fail the workflow if this job fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Download dependencies
        run: go mod download

      - name: Run examples
        run: task examples:run

  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    # Only run after tests pass
    needs: test
    # Only run on push to main branch or manual trigger
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    permissions:
      contents: write # Needed for creating releases and tags
      issues: write   # Needed for creating/labeling issues
      pull-requests: write # Needed for creating/labeling PRs

    steps:
      # Checkout repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # Use GITHUB_TOKEN for auth

      # Setup Node.js for semantic-release
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install semantic-release and plugins
      - name: Install semantic-release
        run: |
          npm init -y
          npm install --save-dev \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/github \
            @semantic-release/git \
            conventional-changelog-conventionalcommits

      # Run semantic-release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release